In [1]:
import numpy as np
import pandas as pd

In [2]:
!pip install ucimlrepo

Requirement already satisfied: ucimlrepo in .\env\lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in .\env\lib\site-packages (from ucimlrepo) (2.3.3)
Requirement already satisfied: certifi>=2020.12.5 in .\env\lib\site-packages (from ucimlrepo) (2026.1.4)
Requirement already satisfied: numpy>=1.26.0 in .\env\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\env\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\env\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in .\env\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.3)
Requirement already satisfied: six>=1.5 in .\env\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import matplotlib.pyplot as plt
from ucimlrepo import fetch_ucirepo

In [13]:
#fetch dataset
data = pd.read_csv("cancer_df/wdbc.data")

In [14]:
data

,842302,M,17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,...,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189
0,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
1,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
2,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
3,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
4,843786,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,...,15.470,23.75,103.40,741.6,0.17910,0.52490,0.5355,0.1741,0.3985,0.12440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
563,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
564,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
565,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
566,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
567,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [15]:
numeric_df = data.select_dtypes(include='number')

In [16]:
numeric_df

,842302,17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,...,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189
0,842517,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
1,84300903,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
2,84348301,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
3,84358402,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
4,843786,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,0.2087,...,15.470,23.75,103.40,741.6,0.17910,0.52490,0.5355,0.1741,0.3985,0.12440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
563,926424,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
564,926682,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
565,926954,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
566,927241,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
567,92751,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [17]:
from sklearn.preprocessing import normalize
numeric_norm1 = normalize(numeric_df, norm='l1')
numeric_norm1

array([[9.95579452e-01, 2.43070102e-05, 2.09983263e-05, ...,
        2.19791147e-07, 3.24960030e-07, 1.05192516e-07],
       [9.99959819e-01, 2.33558694e-07, 2.52063091e-07, ...,
        2.88241558e-09, 4.28566563e-09, 1.03885579e-09],
       [9.99985299e-01, 1.35389000e-07, 2.41613644e-07, ...,
        3.05277298e-09, 7.86963381e-09, 2.05098923e-09],
       ...,
       [9.97449477e-01, 1.78624412e-05, 3.02155029e-05, ...,
        1.52583986e-07, 2.38668040e-07, 8.41471628e-08],
       [9.96106562e-01, 2.21299481e-05, 3.15083193e-05, ...,
        2.84681371e-07, 4.39053873e-07, 1.33209396e-07],
       [9.93006900e-01, 8.30797894e-05, 2.62729128e-04, ...,
        0.00000000e+00, 3.07373808e-06, 7.53606492e-07]], shape=(568, 31))

In [18]:
numeric_norm2 = normalize(numeric_df, norm='l2')
numeric_norm2

array([[9.99996031e-01, 2.44148407e-05, 2.10914788e-05, ...,
        2.20766183e-07, 3.26401614e-07, 1.05659170e-07],
       [1.00000000e+00, 2.33568079e-07, 2.52073219e-07, ...,
        2.88253140e-09, 4.28583784e-09, 1.03889753e-09],
       [1.00000000e+00, 1.35390990e-07, 2.41617196e-07, ...,
        3.05281786e-09, 7.86974950e-09, 2.05101938e-09],
       ...,
       [9.99998817e-01, 1.79080951e-05, 3.02927295e-05, ...,
        1.52973969e-07, 2.39278041e-07, 8.43622310e-08],
       [9.99997103e-01, 2.22163821e-05, 3.16313828e-05, ...,
        2.85793265e-07, 4.40768706e-07, 1.33729678e-07],
       [9.99993447e-01, 8.36643179e-05, 2.64577624e-04, ...,
        0.00000000e+00, 3.09536413e-06, 7.58908677e-07]], shape=(568, 31))

In [19]:
numeric_norm3 = normalize(numeric_df, norm='max')
numeric_norm3

array([[1.00000000e+00, 2.44149376e-05, 2.10915625e-05, ...,
        2.20767059e-07, 3.26402909e-07, 1.05659589e-07],
       [1.00000000e+00, 2.33568079e-07, 2.52073219e-07, ...,
        2.88253140e-09, 4.28583784e-09, 1.03889753e-09],
       [1.00000000e+00, 1.35390990e-07, 2.41617196e-07, ...,
        3.05281786e-09, 7.86974950e-09, 2.05101938e-09],
       ...,
       [1.00000000e+00, 1.79081163e-05, 3.02927653e-05, ...,
        1.52974150e-07, 2.39278324e-07, 8.43623308e-08],
       [1.00000000e+00, 2.22164464e-05, 3.16314744e-05, ...,
        2.85794092e-07, 4.40769983e-07, 1.33730066e-07],
       [1.00000000e+00, 8.36648661e-05, 2.64579358e-04, ...,
        0.00000000e+00, 3.09538442e-06, 7.58913651e-07]], shape=(568, 31))

In [27]:
data_max_col_norm = normalize(numeric_df, axis=0, norm='max')

In [28]:
data_max_col_norm

array([[9.24501312e-04, 7.31768054e-01, 4.52393075e-01, ...,
        6.39175258e-01, 4.14281410e-01, 4.29012048e-01],
       [9.25041221e-02, 7.00462469e-01, 5.40987780e-01, ...,
        8.35051546e-01, 5.44290449e-01, 4.22072289e-01],
       [9.25561324e-02, 4.06261117e-01, 5.18839104e-01, ...,
        8.84879725e-01, 1.00000000e+00, 8.33734940e-01],
       ...,
       [1.01715477e-03, 5.90537175e-01, 7.14867617e-01, ...,
        4.87285223e-01, 3.34136788e-01, 3.76867470e-01],
       [1.01746970e-03, 7.32835290e-01, 7.46690428e-01, ...,
        9.10652921e-01, 6.15697499e-01, 5.97590361e-01],
       [1.01776488e-04, 2.76058342e-01, 6.24745418e-01, ...,
        0.00000000e+00, 4.32509792e-01, 3.39228916e-01]], shape=(568, 31))

In [23]:
string_df = data.select_dtypes(include='string')

In [34]:
string_df

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[568 rows x 0 columns]

In [35]:
data.shape
data.columns

Index(['842302', 'M', '17.99', '10.38', '122.8', '1001', '0.1184', '0.2776',
       '0.3001', '0.1471', '0.2419', '0.07871', '1.095', '0.9053', '8.589',
       '153.4', '0.006399', '0.04904', '0.05373', '0.01587', '0.03003',
       '0.006193', '25.38', '17.33', '184.6', '2019', '0.1622', '0.6656',
       '0.7119', '0.2654', '0.4601', '0.1189'],
      dtype='object')

In [36]:
data.dtypes

842302        int64
M            object
17.99       float64
10.38       float64
122.8       float64
1001        float64
0.1184      float64
0.2776      float64
0.3001      float64
0.1471      float64
0.2419      float64
0.07871     float64
1.095       float64
0.9053      float64
8.589       float64
153.4       float64
0.006399    float64
0.04904     float64
0.05373     float64
0.01587     float64
0.03003     float64
0.006193    float64
25.38       float64
17.33       float64
184.6       float64
2019        float64
0.1622      float64
0.6656      float64
0.7119      float64
0.2654      float64
0.4601      float64
0.1189      float64
dtype: object

In [ ]:
from sklearn.preprocessing import StandardScaler
zscore_scaler = StandardScaler()
data_zscore = zscore_scaler.fit_transform(data)
print("\nZ-score normalization (standardization):\n", data_zscore)

ValueError: could not convert string to float: 'M'